const $=id=>document.getElementById(id);let key='',messages=[];
const provider=$('provider'),keyEl=$('key'),model=$('model'),endpoint=$('endpoint'),endpointLabel=$('endpointLabel'),prompt=$('prompt'),send=$('send'),box=$('messages'),status=$('status');
const defaults={openai:'gpt-5.6-mini',anthropic:'claude-sonnet-4-5',gemini:'gemini-2.5-flash',openrouter:'openai/gpt-5.6-mini',custom:''};
provider.onchange=()=>{model.value=defaults[provider.value]||'';const c=provider.value==='custom';endpoint.classList.toggle('hidden',!c);endpointLabel.classList.toggle('hidden',!c)};provider.onchange();
$('save').onclick=()=>{key=keyEl.value.trim(); if(!key)return; keyEl.value=''; status.textContent='● Key loaded in this tab';status.style.color='#8be28f';prompt.disabled=send.disabled=false;prompt.focus()};
$('clear').onclick=()=>{key='';messages=[];status.textContent='Not connected';status.style.color='';prompt.disabled=send.disabled=true;render()};
$('new').onclick=()=>{messages=[];render()};
function render(){box.innerHTML=messages.length?'':'<div class="empty"><div class="orb">✦</div><h2>Ready when you are</h2><p>Your conversation exists only in this browser tab.</p></div>';messages.forEach(m=>{const row=document.createElement('div');row.className='msg '+m.role;row.innerHTML='<div class="avatar">'+(m.role==='user'?'YOU':'AI')+'</div><div class="bubble"></div>';row.querySelector('.bubble').textContent=m.content;box.appendChild(row)});box.scrollTop=box.scrollHeight}
async function callAI(){const p=provider.value,m=model.value.trim();if(!key||!m)return;const prior=messages.map(x=>({role:x.role,content:x.content}));let text='';
if(p==='openai'||p==='openrouter'||p==='custom'){const url=p==='openai'?'https://api.openai.com/v1/chat/completions':p==='openrouter'?'https://openrouter.ai/api/v1/chat/completions':endpoint.value.trim();if(!url)throw Error('Add a custom endpoint.');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model:m,messages:prior,temperature:.7})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||JSON.stringify(d));text=d.choices?.[0]?.message?.content||''}
else if(p==='anthropic'){const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model:m,max_tokens:2048,messages:prior.map(x=>({role:x.role==='assistant'?'assistant':'user',content:x.content}))})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||JSON.stringify(d));text=d.content?.map(x=>x.text||'').join('')||''}
else {const url='https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(m)+':generateContent?key='+encodeURIComponent(key);const contents=prior.map(x=>({role:x.role==='assistant'?'model':'user',parts:[{text:x.content}]}));const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||JSON.stringify(d));text=d.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||''}
if(!text)throw Error('The provider returned an empty response.');messages.push({role:'assistant',content:text})}
$('composer').onsubmit=async e=>{e.preventDefault();const v=prompt.value.trim();if(!v||!key)return;messages.push({role:'user',content:v});prompt.value='';render();send.disabled=true;status.textContent='● Thinking…';try{await callAI();status.textContent='● Connected'}catch(err){messages.push({role:'assistant',content:'Error: '+err.message});status.textContent='● Request failed'}finally{send.disabled=false;render();prompt.focus()}};
prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('composer').requestSubmit()}});render();
